# Configurable
NUM_IOTS = 1

# Environment
LARGE_SCALE_FADING = 1
LOS_CONSTANT = 1
PATH_LOSS_EXPONENT = 1
EXCESSIVE_PATH_LOSS_NLOS = 3
EXCESSIVE_PATH_LOSS_LOS = 2
CARRIER_FREQUENCY = 1
BLADE_PROFILE_POWER = 1
INDUCED_POWER_HOVER = 1
HOVERING_POWER = 1
MEAN_ROTOR_INDUCED_VELOCITY = 1
FUSELAGE_DRAG_RATIO = 1
ROTOR_SOLIDITY = 1
MEAN_AIR_DENSITY = 1
ROTOR_DISC_AREA = 1
PROPAGATION_PARAMETER = 1


# Constants 
SPEED_OF_LIGHT = 1
